#!/bin/env bash

python3 run.py --bz2 --output=csv_dir ../discogs_dumps --export="artist" --export="label" --export="master" --export "release"
# in order: compress resulting csvs, where to put csvs, export from this dir, export these items

# Create database tables
python3 postgresql/psql.py < postgresql/sql/CreateTables.sql

# Import CSV files
python3 postgresql/importcsv.py /csvdir/*

# This piece of code was generated by ChatGPT after me fighting with git somehow ended up with this file as the
# only unrecoverable one; I gave it what I remembered of the scenario and the rest of this file (which was a
# standard part of the repo), and it said that this was likely what I had (as well as the allow_nulls.sql file). 
# the database tables have constraints on them to not allow NOT NULLs, which is annoying when Discogs is unreliable
# with filling data in; this removes those limits.
psql -U bells -d juniebjonesrecordproject -f allow_nulls.sql


# Configure primary keys and constraints, build indexes
python3 postgresql/psql.py < postgresql/sql/CreatePrimaryKeys.sql
python3 postgresql/psql.py < postgresql/sql/CreateFKConstraints.sql
python3 postgresql/psql.py < postgresql/sql/CreateIndexes.sql


